### PR TITLE
Fix non-ascii characters files disappear in the VirtualBox Shared Folder

### PR DESCRIPTION
**Pull request by ailispaw**
- Fix http://blog.ecoteki.com/webservice/post-2638/
- Related to https://github.com/boot2docker/boot2docker/commit/0de3b8e705a426f19d956241f63f3c2eb5cf1a6c

### CODE REVIEW

**Comment by ailispaw** [comment]
Is this OK on Windows?

---

これって Windows でも大丈夫でしょうか？

**Comment by ixkaito** [comment]
Do you mean this commit might occur errors on Windows?

---

このコミットで Windows がエラー起こすかもしれないということですか？

**Comment by ailispaw** [comment]
I believe this is not harmful on Windows, but I'm just not sure what will happen on Windows with this.

**Comment by ailispaw** [comment]
And it seems not to need this on Windows.
https://twitter.com/K_akiya/status/738625712295288832

**Comment by ixkaito** [comment]
Thanks!
Yes, I also saw that tweet. I'll ask Akiya to help me test this.

**Comment by akiya64** [comment]
hi ixkaito,ailispaw.
I tested with `mount_options: ["iocharset=utf8"]`, 'mounting share folders' succeeded in my Windows10.
I could boot Wocker and start default container.

**Comment by ixkaito** [comment]
Thanks @ailispaw @akiya64 !

**Comment by ailispaw** [comment]
ちなみに、Barge 2.1.2 から `mount_options: ["iocharset=utf8"]` は必要無くなりました。

FYI: `mount_options: ["iocharset=utf8"]` is not required any more since Barge 2.1.2.

**Pull request merged**
