### PR TITLE
Add dumb-init to shutdown a container gracefully

### PR DESCRIPTION
**Pull request by ailispaw**
https://github.com/Yelp/dumb-init

### CODE REVIEW

**Comment by ixkaito** [comment]
I merged your previous pull request. This seems to have conflicts with it.

**Comment by ailispaw** [comment]
I will rebase it later.

**Comment by ailispaw** [comment]
Rebased.

**Comment by ixkaito** [comment]
Many thanks!

**Comment by ailispaw** [comment]
FYI:
I found the actual problem in `mysqld_safe` script to stop the wocker container gracefully.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=208364#103
There is still an issue in the script (@mysql 5.5.47-0+deb8u1) as same as this report.
We need to patch `mysqld_safe` to add `& wait` at the end of the line 146 in it.

``` diff
146c146
<     file) cmd="$cmd >> "`shell_quote_string "$err_log"`" 2>&1" ;;
---
>     file) cmd="$cmd >> "`shell_quote_string "$err_log"`" 2>&1 & wait" ;;
```

I'm not sure this was fixed in the latest mysql-server.

**Comment by ixkaito** [comment]
Thanks.
`mysqld_safe` now shuts down ignoring all signals, doesn't it?
Could you tell me the details of what kind of problem will occur?

**Comment by ailispaw** [comment]
Yes, I believe so.
`supervisord` will kill the subprocess after 10s and exit 0, because of this.
It takes a little longer to stop a container and may break files in the container.

And `dumb-init` can not take care of this.

**Comment by ixkaito** [comment]
Actually, I felt that stopping container takes a little longer than before.
I added a patch, and it works well.

**Comment by ailispaw** [comment]
Nice!

**Pull request merged**
